{control $form begin}
	<!-- hidden fields -->
	<div n:foreach="$form->getComponents(TRUE, 'Nette\Forms\Controls\HiddenField') as $control">{$control->control}</div>
	
	<!-- errors -->
	{assign errors => $form->errors}
	<ul class="error" n:if="$errors" n:block="#errors">
		<li n:foreach="$errors as $error">{$error}</li>
	</ul>

	<!-- groups -->
	<fieldset n:foreach="$form->groups as $group" n:if="$group->controls && $group->getOption('visual')" n:block="#group">
		<legend n:ifset="$group->options['label']">{$group->options['label']}</legend>
		<p n:ifset="$group->options['description']">{$group->options['description']}</p>
		<div n:block="#controls">
			<div class="control" n:foreach="$group->controls as $control" n:if="!$control->getOption('rendered') && $control->getForm(FALSE) === $form" n:block="#pair">
				<div n:block="#label">{if $control instanceof Button || $control instanceof Checkbox}&nbsp;{else}{!$control->label}{/if}</div>
				<div n:block="#control">{!$control->control}{if $control instanceof Checkbox}{!$control->label}{/if}</div>
			</div>
		</div>
	</fieldset>
	
	<!-- non-group -->
	{include #controls, group => $form}
{control $form end}